### ISSUE TITLE
its fine to have user/pass AND tls cert auth in client config

### ISSUE THREAD

**Issue by whohoho** [roburio/openvpn#39]
with this commit: 
https://github.com/roburio/openvpn/commit/d129dfcb36b54b02193da6608115d801b1b955a1

a config would be invalid if you use both user/pass and a client certificate, but that would a valid config for openvpn

**Comment by hannesm** [comment]
uhm, I am struggling a bit. "Its fine" -- Is this a statement from yourself? Does the openvpn man page say so? Do you use an openvpn configuration which uses both? What purpose is it to enable both?

**Comment by whohoho** [comment]
Here is some configs that work fine in openvpn:
https://github.com/whohoho/openvpn/commit/503242f1f5cac17c3d3448b9afd67cc9c51e8242

If you remove the client cert from client config, server will complain.
